#!/bin/sh

scrape_ddg () {
    case "$url_handler" in
	video_player|audio_player|downloader|multimedia_player) die 1 "It appears your url_handler is not a webbrowser" ;;
    esac
    command_exists "ddgr" || die 3 "ddgr is used to scrape duckduckgo"
    search=$1
    output_json_file="$2"

    _tmp_json="${session_temp_dir}/ddg.json"

    ddgr --json "$search" | jq '[.[]|{url: .url, title: .title, ID: 3, channel: "", duration: "", views: "", description: .description}]' >> "$output_json_file"
}
