#!/usr/bin/env sh

#shellcheck disable=SC2154
#shellcheck disable=SC2034

BUTTONS_old_url_handler=$url_handler

post_scrape_buttons () {
    data="$(cat "$ytfzf_video_json_file")"
    echo \
	'[{"ID": "DOWNLOAD", "title": "[DOWNLOAD]", "url": "download", "action": "set-download"}]' \
	'[{"ID": "VIDEO", "title": "[VIDEO]", "url": "video", "action": "set-video"}]' \
	'[{"ID": "AUDIO", "title": "[AUDIO]", "url": "audio", "action": "set-audio"}]' \
	'[{"ID": "DETACH", "title": "[DETACH]", "url": "detach", "action": "set-detach"}]' \
	"$data" > "$ytfzf_video_json_file"
}

handle_custom_action_set_download () {
    BUTTONS_old_url_handler=$url_handler
    url_handler=downloader
    return 1 #continue
}

handle_custom_action_set_video () {
    is_audio_only=0
    url_handler=$BUTTONS_old_url_handler
    return 1 #continue
}

handle_custom_action_set_audio () {
    is_audio_only=1
    url_handler=$BUTTONS_old_url_handler
    return 1 #continue
}

handle_custom_action_set_detach () {
    is_detach=$((is_detach^1))
    url_handler=$BUTTONS_old_url_handler
    return 1 #continue
}
