#!/bin/sh

read -r _ytdl_pref _is_audio_only _is_detach _video_pref _audio_pref url_handler_opts _

ytfzf_video_json_file="${url_handler_opts##*ytfzf_data=}"

playlist_name="${url_handler_opts%%"$(printf '\033')"*}"
playlist_name="${playlist_name#playlist_name=}"

for url in "$@"; do
    jq -r --arg url "$url" '.[]|select(.url==$url)' < "$ytfzf_video_json_file"
done | jq -s '.' >> "$playlist_name"

printf "%s\n" "$@" "has been added to $playlist_name"
