#!/bin/sh

IFS="$(printf '\t')"
read -r ytdl_pref is_audio_only is_detach video_pref audio_pref is_fullscreen url_handler_opts _
unset IFS

[ "$is_fullscreen" -eq 1 ] && url_handler_opts="$url_handler_opts -f"

set -f
case "$is_detach" in
    0) vlc $url_handler_opts "$@" ;;
    1) setsid -f vlc $url_handler_opts "$@" ;;
esac
