#!/bin/sh

case "$1" in
  start)
      for dep in kitty; do
          command_exists "$dep" || die 3 "\n$dep is not installed"
      done
  stop) : ;;
  no-img) kitty +kitten icat --clear --transfer-mode file ;;
  view)
		kitty +kitten icat --clear --transfer-mode file > "$thumbnail_debug_log" 2>&1
        kitty +kitten icat --place "$(( width-2 ))x$(( height-2 ))@${x}x${y}" --scale-up --transfer-mode file "$thumb_path" > "$thumbnail_debug_log" 2>&1 ;;
esac
