#!/bin/bash

action="$1"
case "$action" in
    start)
	command -v "kitty" &> /dev/null  || die 3 "\nkitty is not installed\n" ;;
    view)
	kitty +kitten icat --clear --transfer-mode file
	kitty +kitten icat --place "${5}x${6}@${3}x${4}" --scale-up --transfer-mode file "$2"  ;;
    stop) : ;;
esac
